name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout koda
        uses: actions/checkout@v4

      - name: Postavi Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instaliraj dependencies
        run: npm install --legacy-peer-deps

      - name: Pokreni testove
        run: npm test

      - name: Kreiraj dummy .env
        run: |
          echo "MONGO_URL=mongodb://localhost:27017/test" >> .env
          echo "NEXTAUTH_SECRET=testsecret" >> .env

      - name: Build aplikacije
        run: npm run build